version: '3'
services:
  mysql-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - /containers/mysql/db1
  spring-docker-conainer:
    image: spring-docker-app-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 8088:8080
    volumes:
      - /containers/spring-app-jpa
